use_frameworks!

platform :ios, '9.0'

target 'TRULogining_Example' do
  pod 'TRULogining', :path => '../'
  pod 'TRUNetworking', :path => '../../TRUNetworking'

  target 'TRULogining_Tests' do
    inherit! :search_paths

    pod 'Specta'
    pod 'Expecta'
    pod 'FBSnapshotTestCase'
    pod 'Expecta+Snapshots'
  end
end
